### ISSUE TITLE
Gathering + Viewing of Meta Data of CurreChat usage for a Course

### ISSUE THREAD

**Issue by Catrovitch** [UniversityOfHelsinkiCS/gptwrapper#112]
- [x] Percentage of Students who have opened CurreChat link
- [x] Average Token usage for Course
- [ ] Distribution of Token usage among Students (lower priority)

eg here the info

<img width="990" alt="image" src="https://github.com/UniversityOfHelsinkiCS/gptwrapper/assets/523235/cd5d0679-705b-47d5-86ad-4e1de93ad16c">
