### ISSUE TITLE
Optimize TokenCounter Communicator

### ISSUE THREAD

**Issue by Catrovitch** [UniversityOfHelsinkiCS/gptwrapper#121]
- The current solution is sub-optimal. It works like this:
1. Send message to backend
2. Backend counts tokens
3. Backend sends verdict to Frontend
4. Frontend contains logic for conditionally automatically continuing with sending message to Backend again (tokens used < 10%) or asking for consent (tokens used > 10%).

- New solution:
- Backend handles condition and only goes back to Frontend (user) if tokens used > 10%. Otherwise it continues automatically in backend.

# Todo
- [x] Combine tokenCount and normal stream endpoints into one that handles the logic
- [x] Frontend should only use handleSend() for communicating with backend
- [x] handleSend needs to deal with dynamic response from backend (tokenUsageWarning.message / stream with LLM response)
